/**
 * Helpers (server-only) for creating system notifications.
 *
 * We intentionally bypass RLS using the Supabase Service Role key since
 * notifications are generated by the platform for other users.
 */

'use server'

import { createAdminClient } from '@/lib/shared/db/admin'
import type { Database } from '@/types/database.types'

export type NotificationType = Database['public']['Enums']['notification_type']

export interface CreateSystemNotificationInput {
  userId: string
  type: NotificationType
  title: string
  content: string
  bookingId?: string | null
  announcementId?: string | null
}

export async function createSystemNotification(
  input: CreateSystemNotificationInput
): Promise<{ id: string | null; error: unknown | null }> {
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return {
      id: null,
      error: new Error('SUPABASE_SERVICE_ROLE_KEY is required to create notifications'),
    }
  }

  try {
    const adminClient = createAdminClient()
    const { data, error } = await adminClient
      .from('notifications')
      .insert({
        user_id: input.userId,
        type: input.type,
        title: input.title,
        content: input.content,
        booking_id: input.bookingId ?? null,
        announcement_id: input.announcementId ?? null,
      })
      .select('id')
      .single()

    if (error) {
      return {
        id: null,
        error,
      }
    }

    return {
      id: data?.id ?? null,
      error: null,
    }
  } catch (error) {
    return {
      id: null,
      error,
    }
  }
}
